services:
  rota-db:
    image: postgres:15-alpine
    container_name: rota-db
    environment:
      POSTGRES_DB: rota_db
      POSTGRES_USER: rota_user
      POSTGRES_PASSWORD: rota_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: