version: '3.8'

services:
  rota-db:
    image: postgres:15-alpine
    container_name: rota-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-rotabd}
      POSTGRES_USER: ${DB_USER:-rota_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rota_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: